model:
  name : SimpleDenseYaml

  input_size : 10
  output_size : 5

  layers:
    - type : Linear
      out_features : 3
    
    - type : Linear
      out_features : 4
      
    - type : Linear
      out_features : 5