# Yamlファイルを使ってハイパーパラメータを読み込むサンプルデータ
model:
  name : SimpleDense2

  input_size : 2
  output_size : 5

  layers:
    - type : Affine
      out_features : 3
      initializer : 
        weight : "he"
        bias : "zeros"

    - type: ReLU
    
    - type : Affine
      out_features : 4
      initializer : 
        weight : "he"
        bias : "zeros"

    - type: ReLU
      
    - type : Affine
      out_features : 5
      initializer : 
        weight : "he"
        bias : "zeros"

    - type: ReLU

  loss:
    type : SoftmaxWithLoss