# Yamlファイルを使ってハイパーパラメータを読み込むサンプルデータ
model:
  name : SimpleCNN2

  input_size : 3072

  layers:
    - type : Convolution # (N, 3, 32, 32) → (N, 4, 32, 32)
      out_features : 3072
      out_channels : 4
      in_channels : 3
      kernel_w : 3
      kernel_h : 3
      stride : 1
      padding : 1
      initializer : 
        weight : "he"
        bias : "zeros"
    
    - type : MaxPooling # (N, 4, 32, 32) → (N, 4, 16, 16)
      out_features : 1024
      pool_w : 2
      pool_h : 2
      stride : 2
      padding : 0

    - type: ReLU
      
    - type : Convolution # (N, 4, 16, 16) → (N, 3, 16, 16)
      out_features : 768
      out_channels : 3
      in_channels : 4
      kernel_w : 3
      kernel_h : 3
      stride : 1
      padding : 1
      initializer : 
        weight : "he"
        bias : "zeros"

    - type : MaxPooling # (N, 3, 16, 16) → (N, 3, 8, 8)
      out_features : 1024
      pool_w : 2
      pool_h : 2
      stride : 2
      padding : 0

    - type: ReLU

  loss:
    type : SoftmaxWithLoss