# train:
#   name : VGG16Cifar10
#   batch_size : 1
#   max_epochs : 5
#   lr : 0.001
#   subset : 1
#   sample : True
#   verbose : 2

train:
  name : Cifar10
  batch_size : 64
  max_epochs : 100
  train_size : 0.8
  subset : 0.02
  sample : True
  verbose : 2
  plot_img_idx : 2 # 画像を確認するラベル
  class_num : 10 # 予測クラスの数
  epoch_plots:
  - metric: accuracy
    title: Accuracy
    ylabel: Accuracy
    enabled: true

  - metric: loss
    title: Loss
    ylabel: Loss
    enabled: true

  - metric: precision
    title: Precision
    ylabel: Precision
    enabled: false